version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: chatbot_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  vectordb:
    image: semitechnologies/weaviate:1.20.4
    container_name: chatbot_vectordb
    restart: always
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
    ports:
      - "8080:8080"

  backend:
    build: ./backend
    container_name: chatbot_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - vectordb

  frontend:
    build: ./frontend
    container_name: chatbot_frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  pgdata:
